stages:
  - build
  - test

compile server:
  image: mcr.microsoft.com/dotnet/core/sdk
  stage: build
  only:
    - merge_requests
  script:
    - cd server
    - dotnet build
  artifacts:
    paths:
      - bin/
  when: always

test server:
  image: mcr.microsoft.com/dotnet/core/sdk
  stage: test
  only:
    - merge_requests
  script:
    - cd server
    - dotnet test /p:CollectCoverage=true
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
      - ./**/*coverage.json
