stages:
  - build
  - test

compile client:
  image: node:14-alpine
  stage: build
  only:
    - merge_requests
  script:
    - cd client
    - npm ci
    - npm run build
  when: always

compile server:
  image: mcr.microsoft.com/dotnet/core/sdk:5.0
  stage: build
  only:
    - merge_requests
  script:
    - cd server
    - "dotnet build"
  artifacts:
    paths:
      - bin/
  when: always

test server:
  image: mcr.microsoft.com/dotnet/core/sdk:5.0
  stage: test
  only:
    - merge_requests
  script:
    - cd server
    - "dotnet test /p:CollectCoverage=true"
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
      - ./**/*coverage.json